language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
  global:
    - PACKAGE=pkcs11
    - DISTRO=alpine-3.6
    - DEPOPTS="ctypes ctypes-foreign"
    - FORK_BRANCH=v1.1.0
  matrix:
    - OCAML_VERSION=4.02.3
    - OCAML_VERSION=4.03.0
    - OCAML_VERSION=4.04.0
    - OCAML_VERSION=4.05.0
    - OCAML_VERSION=4.06.0
    - OCAML_VERSION=4.04.0 DISTRO=debian-stable
