language: c
os: linux
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
  global:
    - PACKAGE=pkcs11
    - DISTRO=alpine
    - PINS="pkcs11:. pkcs11-cli:. pkcs11-rev:. pkcs11-driver:."
  jobs:
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.04 PACKAGE=pkcs11-cli
    - OCAML_VERSION=4.04 PACKAGE=pkcs11-rev
    - OCAML_VERSION=4.04 PACKAGE=pkcs11-driver
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.06
    - OCAML_VERSION=4.07
    - OCAML_VERSION=4.08
    - OCAML_VERSION=4.09
    - OCAML_VERSION=4.09 PACKAGE=pkcs11-cli
    - OCAML_VERSION=4.09 PACKAGE=pkcs11-rev
    - OCAML_VERSION=4.09 PACKAGE=pkcs11-driver
    - OCAML_VERSION=4.09 DISTRO=debian-stable
