(** Return values. *)
type t = Pkcs11_CK_ULONG.t

type u =
  | CKR_OK
  | CKR_CANCEL
  | CKR_HOST_MEMORY
  | CKR_SLOT_ID_INVALID
  | CKR_GENERAL_ERROR
  | CKR_FUNCTION_FAILED
  | CKR_ARGUMENTS_BAD
  | CKR_NO_EVENT
  | CKR_NEED_TO_CREATE_THREADS
  | CKR_CANT_LOCK
  | CKR_ATTRIBUTE_READ_ONLY
  | CKR_ATTRIBUTE_SENSITIVE
  | CKR_ATTRIBUTE_TYPE_INVALID
  | CKR_ATTRIBUTE_VALUE_INVALID
  | CKR_DATA_INVALID
  | CKR_DATA_LEN_RANGE
  | CKR_DEVICE_ERROR
  | CKR_DEVICE_MEMORY
  | CKR_DEVICE_REMOVED
  | CKR_ENCRYPTED_DATA_INVALID
  | CKR_ENCRYPTED_DATA_LEN_RANGE
  | CKR_FUNCTION_CANCELED
  | CKR_FUNCTION_NOT_PARALLEL
  | CKR_FUNCTION_NOT_SUPPORTED
  | CKR_KEY_HANDLE_INVALID
  | CKR_KEY_SIZE_RANGE
  | CKR_KEY_TYPE_INCONSISTENT
  | CKR_KEY_NOT_NEEDED
  | CKR_KEY_CHANGED
  | CKR_KEY_NEEDED
  | CKR_KEY_INDIGESTIBLE
  | CKR_KEY_FUNCTION_NOT_PERMITTED
  | CKR_KEY_NOT_WRAPPABLE
  | CKR_KEY_UNEXTRACTABLE
  | CKR_MECHANISM_INVALID
  | CKR_MECHANISM_PARAM_INVALID
  | CKR_OBJECT_HANDLE_INVALID
  | CKR_OPERATION_ACTIVE
  | CKR_OPERATION_NOT_INITIALIZED
  | CKR_PIN_INCORRECT
  | CKR_PIN_INVALID
  | CKR_PIN_LEN_RANGE
  | CKR_PIN_EXPIRED
  | CKR_PIN_LOCKED
  | CKR_SESSION_CLOSED
  | CKR_SESSION_COUNT
  | CKR_SESSION_HANDLE_INVALID
  | CKR_SESSION_PARALLEL_NOT_SUPPORTED
  | CKR_SESSION_READ_ONLY
  | CKR_SESSION_EXISTS
  | CKR_SESSION_READ_ONLY_EXISTS
  | CKR_SESSION_READ_WRITE_SO_EXISTS
  | CKR_SIGNATURE_INVALID
  | CKR_SIGNATURE_LEN_RANGE
  | CKR_TEMPLATE_INCOMPLETE
  | CKR_TEMPLATE_INCONSISTENT
  | CKR_TOKEN_NOT_PRESENT
  | CKR_TOKEN_NOT_RECOGNIZED
  | CKR_TOKEN_WRITE_PROTECTED
  | CKR_UNWRAPPING_KEY_HANDLE_INVALID
  | CKR_UNWRAPPING_KEY_SIZE_RANGE
  | CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT
  | CKR_USER_ALREADY_LOGGED_IN
  | CKR_USER_NOT_LOGGED_IN
  | CKR_USER_PIN_NOT_INITIALIZED
  | CKR_USER_TYPE_INVALID
  | CKR_USER_ANOTHER_ALREADY_LOGGED_IN
  | CKR_USER_TOO_MANY_TYPES
  | CKR_WRAPPED_KEY_INVALID
  | CKR_WRAPPED_KEY_LEN_RANGE
  | CKR_WRAPPING_KEY_HANDLE_INVALID
  | CKR_WRAPPING_KEY_SIZE_RANGE
  | CKR_WRAPPING_KEY_TYPE_INCONSISTENT
  | CKR_RANDOM_SEED_NOT_SUPPORTED
  | CKR_RANDOM_NO_RNG
  | CKR_DOMAIN_PARAMS_INVALID
  | CKR_BUFFER_TOO_SMALL
  | CKR_SAVED_STATE_INVALID
  | CKR_INFORMATION_SENSITIVE
  | CKR_STATE_UNSAVEABLE
  | CKR_CRYPTOKI_NOT_INITIALIZED
  | CKR_CRYPTOKI_ALREADY_INITIALIZED
  | CKR_MUTEX_BAD
  | CKR_MUTEX_NOT_LOCKED
  | CKR_NEW_PIN_MODE
  | CKR_NEXT_OTP
  | CKR_FUNCTION_REJECTED
  | CKR_VENDOR_DEFINED
  | CKR_CS_UNKNOWN of Unsigned.ULong.t

val _CKR_OK : t
val _CKR_CANCEL : t
val _CKR_HOST_MEMORY : t
val _CKR_SLOT_ID_INVALID : t
val _CKR_GENERAL_ERROR : t
val _CKR_FUNCTION_FAILED : t
val _CKR_ARGUMENTS_BAD : t
val _CKR_NO_EVENT : t
val _CKR_NEED_TO_CREATE_THREADS : t
val _CKR_CANT_LOCK : t
val _CKR_ATTRIBUTE_READ_ONLY : t
val _CKR_ATTRIBUTE_SENSITIVE : t
val _CKR_ATTRIBUTE_TYPE_INVALID : t
val _CKR_ATTRIBUTE_VALUE_INVALID : t
val _CKR_DATA_INVALID : t
val _CKR_DATA_LEN_RANGE : t
val _CKR_DEVICE_ERROR : t
val _CKR_DEVICE_MEMORY : t
val _CKR_DEVICE_REMOVED : t
val _CKR_ENCRYPTED_DATA_INVALID : t
val _CKR_ENCRYPTED_DATA_LEN_RANGE : t
val _CKR_FUNCTION_CANCELED : t
val _CKR_FUNCTION_NOT_PARALLEL : t
val _CKR_FUNCTION_NOT_SUPPORTED : t
val _CKR_KEY_HANDLE_INVALID : t
val _CKR_KEY_SIZE_RANGE : t
val _CKR_KEY_TYPE_INCONSISTENT : t
val _CKR_KEY_NOT_NEEDED : t
val _CKR_KEY_CHANGED : t
val _CKR_KEY_NEEDED : t
val _CKR_KEY_INDIGESTIBLE : t
val _CKR_KEY_FUNCTION_NOT_PERMITTED : t
val _CKR_KEY_NOT_WRAPPABLE : t
val _CKR_KEY_UNEXTRACTABLE : t
val _CKR_MECHANISM_INVALID : t
val _CKR_MECHANISM_PARAM_INVALID : t
val _CKR_OBJECT_HANDLE_INVALID : t
val _CKR_OPERATION_ACTIVE : t
val _CKR_OPERATION_NOT_INITIALIZED : t
val _CKR_PIN_INCORRECT : t
val _CKR_PIN_INVALID : t
val _CKR_PIN_LEN_RANGE : t
val _CKR_PIN_EXPIRED : t
val _CKR_PIN_LOCKED : t
val _CKR_SESSION_CLOSED : t
val _CKR_SESSION_COUNT : t
val _CKR_SESSION_HANDLE_INVALID : t
val _CKR_SESSION_PARALLEL_NOT_SUPPORTED : t
val _CKR_SESSION_READ_ONLY : t
val _CKR_SESSION_EXISTS : t
val _CKR_SESSION_READ_ONLY_EXISTS : t
val _CKR_SESSION_READ_WRITE_SO_EXISTS : t
val _CKR_SIGNATURE_INVALID : t
val _CKR_SIGNATURE_LEN_RANGE : t
val _CKR_TEMPLATE_INCOMPLETE : t
val _CKR_TEMPLATE_INCONSISTENT : t
val _CKR_TOKEN_NOT_PRESENT : t
val _CKR_TOKEN_NOT_RECOGNIZED : t
val _CKR_TOKEN_WRITE_PROTECTED : t
val _CKR_UNWRAPPING_KEY_HANDLE_INVALID : t
val _CKR_UNWRAPPING_KEY_SIZE_RANGE : t
val _CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT : t
val _CKR_USER_ALREADY_LOGGED_IN : t
val _CKR_USER_NOT_LOGGED_IN : t
val _CKR_USER_PIN_NOT_INITIALIZED : t
val _CKR_USER_TYPE_INVALID : t
val _CKR_USER_ANOTHER_ALREADY_LOGGED_IN : t
val _CKR_USER_TOO_MANY_TYPES : t
val _CKR_WRAPPED_KEY_INVALID : t
val _CKR_WRAPPED_KEY_LEN_RANGE : t
val _CKR_WRAPPING_KEY_HANDLE_INVALID : t
val _CKR_WRAPPING_KEY_SIZE_RANGE : t
val _CKR_WRAPPING_KEY_TYPE_INCONSISTENT : t
val _CKR_RANDOM_SEED_NOT_SUPPORTED : t
val _CKR_RANDOM_NO_RNG : t
val _CKR_DOMAIN_PARAMS_INVALID : t
val _CKR_BUFFER_TOO_SMALL : t
val _CKR_SAVED_STATE_INVALID : t
val _CKR_INFORMATION_SENSITIVE : t
val _CKR_STATE_UNSAVEABLE : t
val _CKR_CRYPTOKI_NOT_INITIALIZED : t
val _CKR_CRYPTOKI_ALREADY_INITIALIZED : t
val _CKR_MUTEX_BAD : t
val _CKR_MUTEX_NOT_LOCKED : t
val _CKR_NEW_PIN_MODE : t
val _CKR_NEXT_OTP : t
val _CKR_FUNCTION_REJECTED : t
val _CKR_VENDOR_DEFINED : t

include P11_sigs.PKCS with type t := t and type u := u

val typ : t Ctypes.typ
