name: main

on:
  - pull_request
  - push

jobs:
  check-all:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.0
      - run: opam install . --with-doc --with-test --deps-only
      - run: opam exec -- dune build @all @runtest
  check-package:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.07.0
          - 4.12.0
        package:
          - pkcs11
          - pkcs11-cli
          - pkcs11-driver
          - pkcs11-rev
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - run: opam install "${{ matrix.package }}.dev" --with-doc --with-test
